version: '3.8'

services:
  # Vue.js frontend service
  vue-app:
    build:
      context: ../Sentrysk Frontend/
    ports:
      - "8080:8080"
    depends_on:
      - load-balancer
    
  # Backend load balancer
  load-balancer:
    image: nginx:alpine
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - flask-app

  # Flask backend service
  flask-app:
    build:
      context: ../Sentrysk Backend/
    ports:
      - "5000"
    depends_on:
      - mongo-db
    deploy:
      replicas: 3

  # MongoDB service
  mongo-db:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: your_mongo_admin_password
      MONGO_INITDB_DATABASE: dashboard
    volumes:
      - mongodb_data:/data/db
  
  # Scheduled Jobs Services
  scheduled-jobs:
    build:
      context: ../Sentrysk Scheduled Jobs/
    depends_on:
      - flask-app

volumes:
  mongodb_data:
    driver: local
